Cleaning info view. dev_v1 -> develop (test)
andreybog/LetsDoItUkraine pull request #1
Opened 2016-10-09 19:55 UTC by KaterinaNikolaenko

Создан экран с описанием Места уборки

2016-10-09 21:58 UTC, anthony-alekseiev approved these changes

2016-10-10 14:24 UTC, KiriKiri requested changes

2016-10-10 14:24 UTC, KiriKiri commented on LetsDoItUkraine/CleanPlaceViewController.swift
> +    var clean : [String : Any] = ["id": 1,
Эти данные не должны меняться в данном ViewController'e, почему тут var?

2016-10-10 14:24 UTC, KiriKiri commented on LetsDoItUkraine/CleanPlaceViewController.swift
> +    var clean : [String : Any] = ["id": 1,
clean - должна быть типизирована в конкретную структуру

2016-10-10 14:24 UTC, KiriKiri commented on LetsDoItUkraine/CleanPlaceViewController.swift
> +    var user : [String : Any] = ["id": 1,
Аналогично уборке
user - статичен, поэтому let 
и типизирован

2016-10-10 14:24 UTC, KiriKiri commented on LetsDoItUkraine/CleanPlaceViewController.swift
> +        self.cleaningNameCoordinator.text = (user["firstName"] as! String?)! + " " + (user["lastName"] as! String?)!
Если бы юзер был скрыт за структурой этот мтеод можно было бы вынести туда

2016-10-10 14:24 UTC, KiriKiri commented on LetsDoItUkraine/CleanPlaceViewController.swift
>          self.navigationController?.navigationBar.setBackgroundImage(image , for: UIBarMetrics.default)
не ратягивается на весь navigationBar на iPhone6

2016-10-10 14:24 UTC, KiriKiri commented on LetsDoItUkraine/CleanPlaceViewController.swift
> +                                  "photo": "http://beybegi.com/pics/imgs/olympiyskiy.jpg (448KB)"
URL картинки не верный (448КB)
нет логики загрузки картинок

2016-10-12 23:29 UTC, merged