Add DataManager. Add DataManager READ methods. Adjust object-models.
andreybog/LetsDoItUkraine pull request #2
Opened 2016-10-09 21:25 UTC by andreybog

DataManager can read and init next objects:
User, Cleaning, News, RecycleCategory, RecyclePoint

Adjust objects models for import from DB and debug-print.

2016-10-09 21:28 UTC, andreybog commented on LetsDoItUkraine/FirstViewController.swift
> -    ref.child("messages").childByAutoId().setValue(["name" : "Andrey", "text" : "some text"])
Нужно это удалить. Засоряет каждый раз базу.

2016-10-10 14:34 UTC, KiriKiri requested changes

2016-10-10 14:34 UTC, KiriKiri commented on LetsDoItUkraine/DataManager.swift
> +  static func sharedManager() -> DataManager {
зачем тут метод, у нас же любой static let и так lazy переменная?

2016-10-10 14:34 UTC, KiriKiri commented on LetsDoItUkraine/DictionaryInitable.swift
> +  init(withId newId:String, data: [String: AnyObject])
почему newId вынесен отдельно?

2016-10-10 14:38 UTC, andreybog commented on LetsDoItUkraine/DictionaryInitable.swift
> +  init(withId newId:String, data: [String: AnyObject])
потому что из Firebase приходит "ключ" узла и его содержимое(словарь). Этот ключ и есть id структуры.

2016-10-10 14:41 UTC, KiriKiri commented on LetsDoItUkraine/DictionaryInitable.swift
> +  init(withId newId:String, data: [String: AnyObject])
тогда мне кажется лучший вариант это не наследоваться от DictionaryInitiable,
а создать protocol FirabaseInitiable
и сделать protocol extension для всех неоходимых классов
 init(withId newId:String, data: [String: AnyObject]) - режет глаз,
лучше:
init?(ID:String, data:[String:AnyObject])

2016-10-12 23:29 UTC, merged